name: deploy dev

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - 'src/**'

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload Jar file artifact
        uses: actions/upload-artifact@v3
        with:
          name: BackendApplicationJar
          path: build/libs/*.jar

  deploy:
    needs: build-and-upload
    runs-on: self-hosted
    env:
      DEV_DEPLOY_SCRIPT: ${{ secrets.DEV_BACK_DEPLOY_SCRIPT }}
    steps:
      - name: Remove previous version jar
        run: rm -f ~/team-by-team-clone/build/libs/team-by-team-clone*.jar

      - name: Download jar file from artifact
        uses: actions/download-artifact@v3
        with:
          name: BackendApplicationJar
          path: ~/team-by-team-clone/build/libs

      - name: Deploy to Was
        working-directory: /home/ubuntu/
        run: |
          echo "$DEV_DEPLOY_SCRIPT" > dev-deploy.sh
          chmod 700 dev-deploy.sh
          sudo ./dev-deploy.sh
